---

- name: install dependencies
  apt:
    state: latest
    update_cache: yes
    install_recommends: no
    name: 
      - apt-transport-https
      - dirmngr
      - gpg
      - gpg-agent

- name: download latest pulsar editor deb package
  get_url:
    url: https://download.pulsar-edit.dev/?os=linux&type=linux_deb
    dest: /tmp/pulsar.deb
